### ISSUE TITLE
[CodingIntroduction] Enhancments and Feedback

### ISSUE THREAD

**Issue by ipa-fxm** [ipa320/setup#69]
@ipa-mig 
https://github.com/ipa320/setup/pull/68#issuecomment-142926478

**Comment by ipa-mig** [comment]
More Points (some shamelessly copied from #68) for improvements. @ipa320/orga-pull, any more ideas?

- [ ] include some "best practices" for package.xml and CMakeLists.txt. E.g.
    - [ ] sort dependencies alphabetically
    - [ ] for each target, have `add_executable/add_library`, `add_dependencies` and `target_link_libraries` directly after each other
    - [ ] use `add_dependencies(TARGET ${${PROJECT_NAME}_EXPORTED_TARGETS}` and `add_dependencies(TARGET catkin_EXPORTED_TARGETS}` respectively.
    - [ ] delete unnecessary comments out of the files
    - [ ] ...
- [ ] Maybe we should also add a condensed tl;dr version where the most important DO's and DONT's are mentionend, e.g.
    - [ ] Github user name should be `ipa-KÜRZEL`
    - [ ] ...
- [ ] Update [PR Handling](https://github.com/ipa320/setup/blob/master/coding_introduction/CodingIntroduction.md#preparing-your-changes-for-a-pull-request)
    - [ ] PR Review?
    - [ ] Provide a meaninful PR description?
    - [ ] How should a PR look like (small, one feature...)?

**Comment by ipa-fmw** [comment]
as #72 is merged now: can this be closed? Or are we still missing something?

**Comment by ipa-mig** [comment]
I think all is included.

**Comment by ipa-fmw** [comment]
closing this one. If there are new topics, please open a new issue
